---
- name: enable epel repository
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == "CentOS"

- name: install nagios and necessary plugins
  yum:
    name:
      - nagios
      - nagios-plugins
      - nagios-plugins-disk
      - nagios-plugins-http
      - nagios-plugins-load
      - nagios-plugins-ping
      - nagios-plugins-procs
      - nagios-plugins-users
    state: latest
  when: ansible_distribution == "CentOS"

- name: start nagios
  service:
    name: nagios
    state: started
    enabled: true
  when: ansible_distribution == "CentOS"

- name: create nagios group
  tags: group, nagios, centos
  group:
    name: nagios
    state: present

- name: add current user to the nagios group
  tags: user, nagios, centos
  user:
    name: vbearl
    groups: nagios
    append: yes