---
- hosts: all
  become: true
  pre_tasks:

    - name: install updates for centos servers
      tags: always
      dnf:
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: install updates for ubuntu db_servers
      tags: always
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: ubuntu
  become: true
  roles:
    - ubuntu

- hosts: centos
  become: true
  roles:
    - centos